[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
drogon_burn = "61jAmrHDBA7o1FUambLEtJMXDLLhCFujCYxufKm4Ptij"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "/Users/el_loco/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"