[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
drogon_burn = "7y5MbLiNUR6gRbTBbfzr2G3Rh9HsK641VXun8uk725SV"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "https://neat-holy-frost.solana-mainnet.quiknode.pro/65a548a250489db933f10ca99adee34e575f8716/"
wallet = "/Users/adrienfernandezbaca/Key/key.json"


[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"